import { NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from 'react-query'
import { getAllPosts } from 'src/queries/posts/getAllPosts'
import { Post } from 'src/types/db'
import styles from '../styles/Home.module.css'

const Posts: NextPage = () => {
  const { data } = useQuery('posts', getAllPosts, {
    onSuccess(data) {
      console.log('success', data)
    },
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>All Posts</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>All Posts</h1>
        <div>
          {data.map((post: Post, i: number) => {
            return (
              <article key={i}>
                <h3>{post.title}</h3>
                <p>{post.content}</p>
              </article>
            )
          })}
        </div>
      </main>
    </div>
  )
}

export default Posts
