import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Post: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create post</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Add post</h1>
        <form onSubmit={handleFormSubmit}>
          <input name='title' placeholder='title' />
          <input name='content' placeholder='content' />
          <button type='submit'>Submit</button>
        </form>
      </main>
    </div>
  )
}

async function handleFormSubmit(e: React.FormEvent<HTMLFormElement>) {
  e.preventDefault()
  try {
    const post = await fetch('/api/posts', {
      method: 'POST',
      body: JSON.stringify({
        title: 'title',
        content: 'content',
        author: {
          id: 1,
          email: 'test@test.com',
          name: 'test',
          posts: [],
        },
      }),
    })
    console.log(post)
  } catch (error) {
    console.log(error)
  }
}

export default Post
