import type { NextPage } from 'next'
import Head from 'next/head'
import { useMutation } from 'react-query'
import { createUser } from 'src/queries/users/createUser'
import styles from '../styles/Home.module.css'

const User: NextPage = () => {
  const postUser = useMutation(createUser, {
    onMutate(variables) {
      console.log('mutating', variables)
    },
    onError(error, variables, context) {
      console.error('error', error)
    },
    onSuccess(data, variables, context) {
      console.log('success', data)
    },
  })

  function handleFormSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    postUser.mutate({
      email: e.target.email.value,
      name: e.target.name.value,
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create post</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Add user</h1>
        <form onSubmit={handleFormSubmit}>
          <input name='email' placeholder='email' />
          <input name='name' placeholder='name' />
          <button type='submit'>Submit</button>
        </form>
      </main>
    </div>
  )
}

export default User
